### ISSUE TITLE
ColorPixelSearch return value

### ISSUE THREAD

**Issue by Seagulls** [FastFrench/FastFind#2]
I'm using your DLL in my c++ project and I am calling the ColorPixelSearch function which returns either 0 or 1 from what I can tell.

The function returns 1 which tells me it has found the position of a pixel with the color however I am struggling to see how it also returns the co-ordinates of the pixel since its declared as:

int WINAPI ColorPixelSearch(int &XRef, int &YRef, int ColorToFind, int NoSnapShot)

Which just returns an single digit int and not an array of ints or anything?

**Comment by FastFrench** [comment]
Hello,

as you can see, XRef and YRef parameters are references. They get the returned coordinates.
